export type Dossier = {
  id: string;
  name: string;
  role: string;
  kind: "KNOWN" | "SYNTHETIC";
  meta: string;
  body: string;
};

export const DOSSIERS: Dossier[] = [
  {
    id: "K001",
    name: "Chirombe",
    role: "Ancestral line root",
    kind: "KNOWN",
    meta: "Named in the house matrix",
    body: "Root name of the line. The source gives no further biography, so none is invented here.",
  },
  {
    id: "K002",
    name: "Makwengura",
    role: "Great-grandfather",
    kind: "KNOWN",
    meta: "Past generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K003",
    name: "Masawi",
    role: "Grandfather",
    kind: "KNOWN",
    meta: "Past generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K004",
    name: "Masarura",
    role: "Grandmother",
    kind: "KNOWN",
    meta: "Past generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K005",
    name: "Sebastian Karumekangu Masawi",
    role: "Father",
    kind: "KNOWN",
    meta: "Past generation",
    body: "Named in the house matrix as father. No extra life history was in the source.",
  },
  {
    id: "K006",
    name: "Risto Kasirori Masawi",
    role: "Mother",
    kind: "KNOWN",
    meta: "Past and present",
    body: "Named in the house matrix as mother. No extra life history was in the source.",
  },
  {
    id: "K007",
    name: "Tariro Masawi",
    role: "Present house node",
    kind: "KNOWN",
    meta: "Profile note from the source",
    body: "The source describes a founder and strategist, born 17 February 1984 in Zimbabwe, with UK residence noted. This console does not add tracking, portraits, or claims beyond that note.",
  },
  {
    id: "K008",
    name: "Tarry Kupakwashe Masawi",
    role: "Son",
    kind: "KNOWN",
    meta: "Profile note from the source",
    body: "The source describes a son working in music, fashion, and community life. Age was written there as 19. No portrait file was included.",
  },
  {
    id: "K009",
    name: "Kenzi Masawi",
    role: "Adopted son",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K010",
    name: "Tenderayi",
    role: "Brother",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K011",
    name: "Silent",
    role: "Brother",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K012",
    name: "Trymore",
    role: "Brother",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K013",
    name: "Charles",
    role: "Brother",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K014",
    name: "Tatenda",
    role: "Brother",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K015",
    name: "Rhoda",
    role: "Sister",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K016",
    name: "Abigail",
    role: "Sister",
    kind: "KNOWN",
    meta: "Present generation",
    body: "Named in the house matrix. No extra life history was in the source.",
  },
  {
    id: "K017",
    name: "Corinna",
    role: "Deceased sister",
    kind: "KNOWN",
    meta: "Remembered",
    body: "Named in the house matrix and remembered. Nothing further is added.",
  },
  {
    id: "S001",
    name: "Herculean Prometheus",
    role: "Synthetic strategist node",
    kind: "SYNTHETIC",
    meta: "Not a real person",
    body: "A fictional node from the profile fragment: defence design, chess, robotics. It is a simulation label, not a human and not a detected being.",
  },
  {
    id: "S002",
    name: "Haszeldonia",
    role: "Synthetic culture node",
    kind: "SYNTHETIC",
    meta: "Not a real person",
    body: "A fictional node from the profile fragment, described there as a bridge across language and music. Simulation only.",
  },
  {
    id: "S003",
    name: "Zioncore",
    role: "Synthetic signal node",
    kind: "SYNTHETIC",
    meta: "Not a real person",
    body: "A fictional node from the profile fragment. The name is a module label inside this console, not an outside intelligence.",
  },
  {
    id: "S004",
    name: "Deputy Adam",
    role: "Synthetic operations node",
    kind: "SYNTHETIC",
    meta: "Not a real person",
    body: "A fictional operations node from the profile fragment. It does not automate anything outside this browser.",
  },
];
